---
- name: update packeges
  yum:
    name: '*'
    state: latest

- name: set vagrant insecure authorized keys
  authorized_key:
    user: vagrant
    key: "{{ lookup('file', 'files/vagrant.pub') }}"
    state: present

- name: install packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - epel-release
    - git
